# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Blocq.io' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Blocq.io
	
    pod 'Alamofire', '~> 4.7.2'
    pod 'Kingfisher', '~> 4.8.0'
    pod 'Charts'
    pod 'SwiftMessages', '~> 4.1.0'
    #Reactive
    pod 'ReactiveCocoa', '~> 7.0.1'
    pod 'ReactiveSwift', '~> 3.0.0'
    pod 'Fabric'
    pod 'Crashlytics'

end
